torchrun --nproc_per_node=4 train/train_encoder.py \
        --data results/rac_c_1k \
        --model pretrained/SmolLM2-135M \
        --out results/rac_c_1k/rac_encoder_run2 \
        --k 16 \
        --k-chunk 4 \
        --n-latents 128 \
        --n-heads 8 \
        --n-layers 2 \
        --src-layer -2 \
        --tau 0.4 \
        --softmin-detach \
        --seed 42 \
        --epochs 4 \
        --queries-per-step 4 \
        --lr 3e-4 \
        --weight-decay 0.01 \
        --grad-clip 1.0 \
        --log-every 10 \
        --log-top-k 4 \
        --wandb \
        --wandb-project rac
