torchrun --nproc_per_node=1 train/train_reranker.py \
        --data results/rac_c_1k \
        --model pretrained/SmolLM2-135M \
        --out results/rac_c_1k/rac_reranker \
        --proj-dim 256 \
        --dropout 0.1 \
        --epochs 8 \
        --queries-per-step 16 \
        --lr 1e-3 \
        --seed 42 \
        --wandb \
        --wandb-project rac-reranker
